name: Harttle Land
description: 欢迎访问 Harttle 的个人主页，这里记录了 harttle 关于计算机技术的文章、个人信息与相册，以及有用的资源分享和下载。
url: http://harttle.github.io
markdown: redcarpet
redcarpet:
  extensions: [no_intra_emphasis,tables,autolink]
pygments: true
permalink: none
blog_categories:
    - linux
    - web
    - "笔记"
    - "日志"
album_categories:
    - "个人"
    - "摄影"
resource_categories:
    - "论文"
    - "作业"
