name: Harttle Land
description: Harttle 的个人主页
url: http://harttle.github.io
markdown: redcarpet
redcarpet:
  extensions: [no_intra_emphasis,tables,autolink]
pygments: true
permalink: none
blog_categories:
    - linux
    - web
    - "笔记"
    - "日志"
album_categories:
    - "个人"
    - "摄影"
resource_categories:
    - "论文"
    - "作业"
